#  Tonelada métrica per cápita de emisiones de CO2

## Carga de archivo

In [1]:
pip install seaborn

Collecting seaborn
  Downloading seaborn-0.11.2-py3-none-any.whl (292 kB)
     |████████████████████████████████| 292 kB 4.8 MB/s eta 0:00:01
Requirement already satisfied: scipy>=1.0 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from seaborn) (1.4.1)
Requirement already satisfied: matplotlib>=2.2 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from seaborn) (3.2.1)
Requirement already satisfied: pandas>=0.23 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from seaborn) (1.0.4)
Requirement already satisfied: numpy>=1.15 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from seaborn) (1.18.5)
Requirement already satisfied: kiwisolver>=1.0.1 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from matplotlib>=2.2->seaborn) (1.2.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from matplotlib>=2.2->seaborn) (2.4.7)
Requirement already satisfied: python-dateutil>=2.1 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from matplotlib>=2.2->seaborn) (2.8.1)
Requirement already satisfied: cycler>=0.10 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from matplotlib>=2.2->seaborn) (0.10.0)
Requirement already satisfied: six in /srv/conda/envs/notebook/lib/python3.7/site-packages (from cycler>=0.10->matplotlib>=2.2->seaborn) (1.16.0)
Requirement already satisfied: pytz>=2017.2 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from pandas>=0.23->seaborn) (2020.1)
Installing collected packages: seaborn
Successfully installed seaborn-0.11.2
Note: you may need to restart the kernel to use updated packages.

In [6]:
pip install xlrd

Collecting xlrd
  Downloading xlrd-2.0.1-py2.py3-none-any.whl (96 kB)
     |████████████████████████████████| 96 kB 3.0 MB/s eta 0:00:011
Installing collected packages: xlrd
Successfully installed xlrd-2.0.1
Note: you may need to restart the kernel to use updated packages.

In [7]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.0.9-py2.py3-none-any.whl (242 kB)
     |████████████████████████████████| 242 kB 4.7 MB/s eta 0:00:01
Collecting et-xmlfile
  Downloading et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.0.9
Note: you may need to restart the kernel to use updated packages.

In [8]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [9]:
%ls datasets/

adult.csv                                       cwurData.csv
airline_data.csv                                data.csv
antropometria00.csv                             headbrain.csv
antropometria-dataset.csv                       mic2.xlsx
API_EN.ATM.CO2E.PC_DS2_en_csv_v2_3159114.csv    mic.xlsx
API_EN.ATM.CO2E.PC_DS2_en_excel_v2_3158884.xls  movies.csv
Book3.csv                                       nhanes_2015_2016.csv
Canada.xlsx                                     pokemon.csv
Cartwheeldata.csv                               sample_pivot.csv
census.csv                                      tips.csv
CO2emissions.xlsx                               weight-height.csv
coches.csv

In [13]:
df=pd.read_excel('datasets/API_EN.ATM.CO2E.PC_DS2_en_excel_v2_3158884.xls',
                 sheet_name='Data',
                skiprows=range(3))

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Aruba,ABW,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,204.631696,208.837879,226.081890,214.785217,207.626699,185.213644,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,0.906060,0.922474,0.930816,0.940570,0.996033,1.047280,...,1.005338,1.021646,1.031833,1.041145,0.987393,0.971016,0.959978,0.933541,NaN,NaN
2,Afghanistan,AFG,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,0.046057,0.053589,0.073721,0.074161,0.086174,0.101285,...,0.407074,0.335351,0.263716,0.234037,0.232176,0.208857,0.203328,0.200151,NaN,NaN
3,Africa Western and Central,AFW,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,0.090880,0.095283,0.096612,0.112376,0.133258,0.184803,...,0.497023,0.490867,0.504655,0.507671,0.480743,0.472959,0.476438,0.515544,NaN,NaN
4,Angola,AGO,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,0.100835,0.082204,0.210533,0.202739,0.213562,0.205891,...,1.216317,1.204799,1.261542,1.285365,1.260921,1.227703,1.034317,0.887380,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
262,"Yemen, Rep.",YEM,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,0.011038,0.013599,0.012729,0.014518,0.017550,0.017926,...,0.869051,0.804146,1.047834,1.034330,0.536269,0.400468,0.361418,0.326682,NaN,NaN
263,South Africa,ZAF,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,5.727223,5.832621,5.887168,5.961337,6.332343,6.616545,...,7.867124,8.076633,8.137333,8.213158,7.671202,7.564451,7.632729,7.496645,NaN,NaN
264,Zambia,ZMB,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,NaN,NaN,NaN,NaN,0.946606,1.096875,...,0.218210,0.277909,0.284058,0.311693,0.319282,0.341615,0.414748,0.446065,NaN,NaN
265,Zimbabwe,ZWE,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,NaN,NaN,NaN,NaN,1.034904,1.166242,...,0.891090,0.923360,0.925816,0.894256,0.897598,0.783303,0.718570,0.849793,NaN,NaN

In [14]:
df.columns=list(map(str,df.columns))

In [15]:
all(isinstance(column,str)for column in df.columns)

True

## Introducción

Este conjunto de datos fue generado por el centro Carbon Dioxide Information Analysis Center de Tennessee en los Estados Unidos y fue extraido de la página de The World Bank.

Enlace a The World Bank para descargar: https://data.worldbank.org/indicator/EN.ATM.CO2E.PC?view=chart

### Descripción de los datos

En este set de datos podemos encontrar las toneladas métricas de emisiones de CO2 (dioxido de carbono) de 199 paises de los años 1964-2018.

La tabla tiene las siguientes columnas:

In [16]:
df.columns

Index(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
       '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020'],
      dtype='object')

* 'Country Name' es un variable cualitativa, explica los paises bajo estudio
* 'Country Code' es un variable cualitativa, explica el codigo de los paises bajo estudio
* 'Indicator Name' es un variable cualitativa, explica el tipo de indicador utilizado en el estudio
* 'Indicator Code' es un variable cualitativa, explica el explica el codigo del indicador bajo estudio
1964 - 2018 es una variable cuantitativa, explica las cantidad de toneladas metricas de emisiones de CO2 por cada país bajo estudio

## Pregunta de Investigación 1: ¿Cuáles son los países que han emiten mas CO2 durante los años? ¿Cuáles son los que han emitido menos CO2?

### Conclusión

## Pregunta de Investigación 2:

### Conclusión

## Pregunta de Investigación 3: ¿Desde que México ratificó el acuerdo de Paris en el 2016, se ha visto un cambio en sus emisiones de CO2?

### Conclusión

## Limitaciones

## Siguientes pasos